spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&serverTimezone=Europe/Madrid
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: false

invault:
  realtime:
    allowed-origins: ${INVAULT_REALTIME_ALLOWED_ORIGINS}
  security:
    jwt:
      secret: ${INVAULT_JWT_SECRET}
