package com.invault.inventory.stock;

import java.util.List;

import org.springframework.stereotype.Component;

import com.invault.inventory.batches.Batch;
import com.invault.inventory.products.Product;
import com.invault.inventory.stock.dto.StockMovementResponseDTO;
import com.invault.inventory.suppliers.Supplier;
import com.invault.inventory.users.User;

/**
 * Mapper responsible for converting StockMovement entities into response DTOs.
 *
 * Stock movements are historical records, so this mapper only exposes a toResponseDTO method.
 * Creation will be handled later by StockService to preserve business rules and traceability.
 */
@Component
public class StockMovementMapper {

    /**
     * Converts a StockMovement entity into a StockMovementResponseDTO.
     *
     * @param stockMovement entity from the database
     * @return response DTO ready to be sent to the client
     */
    public StockMovementResponseDTO toResponseDTO(StockMovement stockMovement) {
        if (stockMovement == null) {
            return null;
        }

        Product product = stockMovement.getProduct();
        Batch batch = stockMovement.getBatch();
        User user = stockMovement.getUser();
        Supplier supplier = stockMovement.getSupplier();

        return new StockMovementResponseDTO(
                stockMovement.getId(),

                product != null ? product.getId() : null,
                product != null ? product.getSku() : null,
                product != null ? product.getName() : null,

                batch != null ? batch.getId() : null,
                batch != null ? batch.getBatchCode() : null,

                user != null ? user.getId() : null,
                user != null ? user.getUsername() : null,

                supplier != null ? supplier.getId() : null,
                supplier != null ? supplier.getName() : null,

                stockMovement.getMovementType(),
                stockMovement.getQuantity(),
                stockMovement.getPreviousBatchQuantity(),
                stockMovement.getNewBatchQuantity(),
                stockMovement.getReason(),
                stockMovement.getMovementDate()
        );
    }

    /**
     * Converts a list of StockMovement entities into a list of StockMovementResponseDTO objects.
     *
     * @param stockMovements list of entities from the database
     * @return list of response DTOs ready to be sent to the client
     */
    public List<StockMovementResponseDTO> toResponseDTOList(List<StockMovement> stockMovements) {
        if (stockMovements == null) {
            return List.of();
        }

        return stockMovements.stream()
                .map(this::toResponseDTO)
                .toList();
    }
}

/*
 * Explanation:
 * StockMovementMapper centralizes the conversion from StockMovement to StockMovementResponseDTO.
 * It intentionally does not create StockMovement entities from request DTOs because stock movements
 * must be generated by StockService after validating stock rules and calculating quantity changes.
 */